### ISSUE TITLE
I want add Windows support?

### ISSUE THREAD

**Issue by SeanTolstoyevski** [cckuailong/py2so#3]
Hello @cckuailong ,

Other than Ubuntu and CentOS, do we have problems adding Windows support?

I would like to make Windows compatible unless there are huge problems.

Yours.

**Comment by cckuailong** [comment]
Thx, py2so refers to Cython. Unfortunately, Use Cython on Win is a complex work, maybe have to install the right version of the MVC++ or others. If you want to Encrypt the py files on win, you can step to the PyPi--Cython, and it can give you a pyd file (equals to so file on Linux)

**Comment by cckuailong** [comment]
- Step 1: make a setup.py file
```
from distutils.core import setup
from distutils.extension import Extension
from Cython.Build import cythonize
from Cython.Distutils import build_ext

filename = 'test'
full_filename = 'test.py'
extentions = [Extension(filename, [full_filename])]

setup(
    cmdclass={'build_ext': build_ext},
    ext_modules = cythonize(extentions, language_level=3)
)
```
- Step 2: python setup.py build_ext --inplace
